[versions]
fpgradle = "3.2.0"
kotlin = "2.2.21"
coroutines = "1.10.2"
serialization = "1.9.0"
annotations = "26.0.2-1"
fastutil = "8.5.16"

fplib = "1.10.4"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutinesJdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlinx-serializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "annotations"}
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
fplib = { module = "com.falsepattern:falsepatternlib-mc1.7.10", version.ref = "fplib" }

[plugins]
fpgradle = { id = "com.falsepattern.fpgradle-mc", version.ref = "fpgradle" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }